### PR TITLE
Reusable actions and update chrome(driver)

### PR DESCRIPTION
**Pull request by JJWTimmer**
Use latest actions and make a reuable file for base actions

### CODE REVIEW

**Comment by JJWTimmer** [comment]
Screenshots are still mangled as per #33, so this solves only 'reuse' of workflow steps.
I also believe it needs more testing or love, maybe the artifact step is not even needed.

**Comment by JJWTimmer** [comment]
Artifacts step is needed, so this is the most re-usable as I can get it, I think.

**Comment by JJWTimmer** [comment]
@jurgenvinju got on opinion on this? I know the screenshots are fixed by you, but this still has the benefit of updated chrome and of no github actions duplication

**Comment by jurgenvinju** [comment]
I like simplifications like this. Thanks @JJWTimmer

**Review by jurgenvinju — APPROVED** [review]

**Comment by jurgenvinju** [comment]
Pls merge when you are ready @JJWTimmer

**Pull request merged**
