### PR TITLE
Update Derivative.md

### PR DESCRIPTION
**Pull request by tdadadavid**
* Update the mathematical expressions  for easy comprehension
* Add a note on for variables `con` & `var` for non-technical people to understand
* made some grammatical fixes

### CODE REVIEW

**Comment by JJWTimmer** [comment]
Hi @tdadadavid, thanks for the submission!

@jurgenvinju can you verify the textual changes please? It's a small one.

**Review by jurgenvinju — APPROVED** [review]
This is very nice. Thanks!

**Comment by tdadadavid** [comment]
I noticed an issue going to the site, I will look into this and fix it.

The mathematical expression works well on github

image

but not on the live docs.
image

**Comment by JJWTimmer** [comment]
Please note the website uses Docusaurus 2.x and is different from Github
Markdown. Please see here:
https://docusaurus.io/docs/2.x/markdown-features/math-equations

Kind regards / Met vriendelijke groet,

Jasper Timmer



Op vr 5 jan 2024 om 19:40 schreef King ***@***.***>:

**Pull request merged**
